#ifndef RESOUCES_H
#define RESOUCES_H

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Exsylor.rc
//
#define IDR_MAINFRAME                   2
#define IDR_EXSTYPE                     3
#define IDR_REG_SCRIPT                  4
#define IDR_REG_EDIT                    5
#define IDR_SCRIPTTYPE                  6
#define IDR_SCROPTTYPE                  7
#define IDS_NOT_SAVE_SMP                7
#define IDR_EMPTY                       8
#define IDR_VIEW_BM                     8
#define IDR_EXPLAN                      9
#define IDR_WORD_EDIT                   10
#define IDR_WORD_SCRIPT                 11
#define IDS_EXIST_SMP                   12
#define IDR_SYSTEM                      12
#define IDS_ERROR_FILE                  13
#define IDS_ERROR_FILE2                 14
#define IDD_ABOUTBOX                    51
#define IDD_MODELSCRIPT                 52
#define IDD_FORMA                       53
#define IDD_GEN_DAT                     54
#define IDD_IND                         55
#define IDD_EDIT_NAME                   56
#define IDD_SEL_ATTR                    57
#define IDD_GEN_KNOW                    58
#define IDD_IND_TABLE                   59
#define IDD_RECOGNITION                 60
#define IDB_BITMAP1                     100
#define IDB_BITMAP2                     101
#define IDB_BITMAP3                     102
#define IDB_BITMAP4                     103
#define IDB_BITMAP5                     104
#define IDB_BITMAP6                     105
#define IDB_BITMAP7                     106
#define IDB_BITMAP8                     107
#define IDB_BITMAP9                     108
#define IDB_BITMAP10                    109
#define IDB_BITMAP11                    110
#define IDB_BITMAP12                    111
#define IDB_BITMAP13                    112
#define IDB_BITMAP14                    113
#define IDB_BITMAP15                    114
#define IDB_BITMAP16                    115
#define IDI_DIRECT                      116
#define IDI_EMPT                        117
#define IDI_WORD_SCRIPT                 118
#define IDI_WORD_ED                     119
#define IDS_ERR_ATR                     130
#define IDS_ERR_VAL                     131
#define IDS_IMPOSSIBLE                  132
#define IDS_MODE_IF                     133
#define IDS_MODE_THEN                   134
#define IDS_REG_SEL                     135
#define IDS_REALLY                      136
#define IDS_SYSTEM                      137
#define IDS_CR_DATA                     138
#define IDS_ED_DATA                     139
#define IDS_CR_KNOW                     140
#define IDS_ED_KNOW                     141
#define IDS_DESC_OBJ                    142
#define IDS_CH_AIM                      143
#define IDS_BMVIEW                      144
#define IDS_REDUCT_NOT                  145
#define IDS_L_CONTRADICT                146
#define IDS_L_CONTRA_REGUL              147
#define IDS_L_INFER_EVIDENT             148
#define IDS_L_INFER_TOO_LONG            149
#define IDS_L_VALID_SET                 150
#define IDS_L_NOT_VAL                   151
#define IDS_EXPLANVIEW                  152
#define IDS_L_NOT_VAL_1                 153
#define IDS_L_NOT_VAL_2                 154
#define IDS_DELETE_REG                  155
#define IDS_L_STATEM_3                  156
#define IDS_L_PRESENT_CONTRA            157
#define IDS_L_STATEM_4                  158
#define IDS_REC_DONE                    159
#define IDS_L_ADD_EXP                   160
#define IDS_L_CONTRADICT2               161
#define IDS_TASK_DESC                   162
#define IDS_ANY_VAL                     163
#define IDS_L_STATEM_5                  164
#define IDS_L_STATEM_6                  165
#define IDS_L_PROOF_ADD                 166
#define IDS_L_PROOF_ADD0                167
#define IDS_L_PROOF_ADD1                168
#define IDS_L_PROOF_ADD2                169
#define IDS_L_PROOF_ADD3                170
#define IDS_SYSMODE                     171
#define IDS_NOT_REGUL_FOR_IND           172
#define IDS_L_LEN_PROOF                 173
#define IDS_L_0_PROOF_VAL               174
#define IDD_BLOCK_SEL                   174
#define IDS_L_0_PROOF_VAL2              175
#define IDS_L_PROOF_CONTRA              176
#define IDS_L_PROOF_CONTRA_1            177
#define IDS_L_0_PROOF_ATR               178
#define IDS_L_PROOF_ATR0                179
#define IDS_L_STATEM                    180
#define IDS_LAST_ROW_DEL                181
#define IDS_DELETE_MOD                  182
#define IDS_SMP_SEL                     183
#define IDS_DELETE_SMP                  184
#define IDS_MOD_SEL                     185
#define IDS_NOT_SAVE_REG                186
#define IDS_EXIST_REG                   187
#define IDC_COMBO1                      1000
#define IDC_COMBO2                      1001
#define ID_EDIT                         1002
#define ID_DELETE                       1003
#define IDC_EDIT1                       1004
#define IDC_NAME_MOD                    1005
#define IDC_NUM_ATTRIBE                 1006
#define ID_IMPORT                       1006
#define IDC_NUM_VALUE                   1007
#define IDC_NAME_KB                     1008
#define IDC_NUM_KB                      1009
#define IDC_NUM_VALUE2                  1010
#define IDC_NUM_DB                      1011
#define IDC_NUM_VALUE3                  1012
#define IDC_NAME_KB2                    1013
#define IDC_NAME_DB                     1013
#define IDC_EDIT2                       1014
#define IDC_EDIT3                       1015
#define IDC_EDIT4                       1016
#define IDC_EDIT5                       1017
#define IDC_EDIT6                       1018
#define IDC_EDIT7                       1019
#define IDC_BUTTON1                     1020
#define IDC_CHECK1                      1021
#define IDC_LIST1                       1022
#define IDC_CHECK2                      1023
#define IDC_CHECK3                      1024
#define IDC_STATIC1                     1025
#define IDC_STATIC2                     1026
#define IDC_STATIC3                     1027
#define IDC_STATIC4                     1028
#define IDC_STATIC5                     1029
#define IDC_STATIC6                     1030
#define IDC_STATIC7                     1031
#define IDC_NUM_MOD                     1033
#define IDOK2                           1034
#define ID_VIEW_EXIT                    32771
#define ID_P_FORMULA                    32773
#define ID_P_MATRIX                     32774
#define ID_STEP_NEXT                    32775
#define ID_STEP_PREV                    32776
#define ID_STEP_FIRST                   32777
#define ID_STEP_LAST                    32778
#define ID_VIEW_EXPLAN_EXIT             32779
#define ID_KNOW_SAVE                    32780
#define ID_KNOW_CLOSE                   32781
#define ID_REG_READ                     32782
#define ID_REG_WRITE                    32783
#define ID_REG_INSERT                   32784
#define ID_REG_ADD                      32785
#define ID_REG_DEL                      32786
#define ID_REG_CLEAR                    32787
#define ID_REG_NEXT                     32788
#define ID_RECOGN_OBJECT                32789
#define ID_RECOGN_FULL                  32790
#define ID_RECOGN_ATR                   32791
#define ID_RECOGN_VAL                   32792
#define ID_RECOGN_PROOF                 32793
#define ID_SYSTEM                       32794
#define ID_RECOGNITION                  32795
#define ID_EXPERT                       32796
#define ID_MODEL_NEW                    32797
#define ID_MODEL_OPEN                   32798
#define ID_MODEL_EDIT                   32799
#define ID_MODEL_DEL                    32800
#define ID_KNOW_NEW                     32801
#define ID_KNOW_OPEN                    32802
#define ID_KNOW_EDIT                    32803
#define ID_KNOW_DELETE                  32804
#define ID_KNOW_REDUCT                  32805
#define ID_KNOW_GEN                     32806
#define ID_DATA_NEW                     32807
#define ID_DATA_OPEN                    32808
#define ID_DATA_EDIT                    32809
#define ID_DATA_DELETE                  32810
#define ID_DATA_IND                     32811
#define ID_DATA_GEN                     32812
#define ID_DATA_SAVE                    32813
#define ID_DATA_CLOSE                   32814
#define ID_DATA_READ_SMP                32815
#define ID_DATA_WRITE_SMP               32816
#define ID_DATA_INSERT_SMP              32817
#define ID_DATA_ADD_SMP                 32818
#define ID_DATA_DEL_SMP                 32819
#define ID_DATA_CLEAR_SMP               32820
#define ID_MODEL_EXPORT                 32843
#define ID_KB_EXPORT                    32845
#define ID_KB_IMPORT                    32846
#define ID_DB_EXPORT                    32847
#define ID_DB_IMPORT                    32848
#define ID_INDICATOR_TASK               59142

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32854
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif


#endif // RESOUCES_H
